"""Builds the 24 enemy / boss spritesheets (style B, 3D -> pixel art), finished by the real Aseprite.
For every character: render frames -> assets/enemies/<key>_src.aseprite (layers body + rim) -> aseprite.exe (Lua): indexed palette -> assets/enemies/<key>.aseprite
-> aseprite.exe exports the sheet + data -> assets/enemies/<key>.png|json -> js/enemySprites.js
usage: python tools/build_enemy_sheets.py [keys...]"""
import base64, io, json, os, subprocess, sys
from multiprocessing import Pool
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import enemy3d as E3, asekit
from make_enemy_sprites import ROSTER, frame_plan

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'
EU = 1.22          # must match EU in js/util.js

def enemy_yaws(name):
    n = name
    table = [('spin_s', (110, 50, 30)), ('flykick', (16, 48, -10)), ('slam', (22, 50, 10)), ('charge', (20, 50, 14)), ('jab', (28, 52, 14)), ('hay', (30, 52, 18)),
             ('throw', (26, 52, 14)), ('point', (24, 52, 10)), ('low', (22, 50, -8)), ('hurt2', (16, 40, -12)), ('hurt', (18, 44, -8)), ('tumble', (20, 40, 0)),
             ('down', (8, 30, 0)), ('getup0', (8, 30, 0)), ('getup1', (16, 44, 0)), ('arms_up', (28, 52, 0))]
    for key, val in table:
        if n.startswith(key): return val
    return (28, 52, 6)

def ase(args):
    r = subprocess.run([ASEPRITE, '-b'] + args, capture_output=True, text=True, timeout=300)
    if r.returncode != 0: raise RuntimeError('aseprite failed: ' + ' '.join(args) + '\n' + r.stdout + r.stderr)

def build_one(sp):
    key = sp['key']; ch = E3.Char3D(sp, EU); plan = frame_plan(sp); fs = ch.FS
    frames = []
    for name, pose, wind in plan:
        yb, yh, tw = enemy_yaws(name); w = (max(-4, min(5, pose['lean'] * 8 + wind[0])), wind[1]); body, rim = ch.render(pose, yb, yh, tw, w); frames.append((name, body, rim))
    out = os.path.join(ROOT, 'assets', 'enemies'); os.makedirs(out, exist_ok=True)
    src, final = os.path.join(out, key + '_src.aseprite'), os.path.join(out, key + '.aseprite')
    asekit.write_ase(src, fs, fs, [{'layers': [b, r], 'duration': 90} for _n, b, r in frames], [], layer_names=('body', 'rim'))
    ase([src, '--script-param', 'out=' + final.replace(chr(92), '/'), '--script', os.path.join(ROOT, 'tools', 'ase', 'hero_finalize.lua')])
    png, js = os.path.join(out, key + '.png'), os.path.join(out, key + '_ase.json')
    ase([final, '--sheet', png, '--data', js, '--format', 'json-array', '--sheet-type', 'rows', '--sheet-columns', '8'])
    aj = json.load(open(js)); sheet = Image.open(png).convert('RGBA')
    jf = {n: {'frame': aj['frames'][i]['frame'], 'duration': 90} for i, (n, _b, _r) in enumerate(frames)}
    meta = {'app': 'veexing-force enemy generator v2 (3D->pixel art, aseprite export)', 'image': key + '.png', 'size': {'w': sheet.width, 'h': sheet.height}, 'anchor': {'x': ch.OX, 'y': ch.OY}, 'scale': round(ch.k, 3)}
    data = {'frames': jf, 'meta': meta}; json.dump(data, open(os.path.join(out, key + '.json'), 'w'))
    os.remove(src); os.remove(js)
    buf = io.BytesIO(); sheet.save(buf, 'PNG', optimize=True)
    return key, base64.b64encode(buf.getvalue()).decode(), data, len(frames)

if __name__ == '__main__':
    keys = sys.argv[1:]; roster = [s for s in ROSTER if not keys or s['key'] in keys]
    with Pool(min(8, len(roster))) as pool: results = pool.map(build_one, roster)
    if not keys:
        lines = ['// generated by tools/build_enemy_sheets.py - do not edit', 'const ENEMY_SHEETS = {']
        for key, b64, data, n in results: lines.append("  %s: { img: 'data:image/png;base64,%s', json: %s }," % (key, b64, json.dumps(data)))
        lines.append('};'); open(os.path.join(ROOT, 'js', 'enemySprites.js'), 'w').write('\n'.join(lines) + '\n')
    print('characters', len(results), 'frames', sum(r[3] for r in results))
