"""Put YOUR hand-drawn hero into the game.
  1. draw in assets/hero_workspace.aseprite (layers OMBRE_SOL..LISERE_NEON; REF_*, GUIDES are references and are NOT exported)
  2. python tools/import_hero_sheet.py [path/to/workspace.aseprite]
It exports the sheet with the real Aseprite (CLI), checks that frames are really drawn (never overwrites the current hero with an empty
sheet), backs up the current sheet once, then rewrites assets/hero.png + hero.json + js/heroSprites.js. Reload the game.
Options: --force  import even if some frames are empty     --keep-shadow  also export the OMBRE_SOL layer"""
import base64, io, json, os, shutil, subprocess, sys, tempfile
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]; force = '--force' in sys.argv; keep_shadow = '--keep-shadow' in sys.argv
    ws = args[0] if args else os.path.join(ROOT, 'assets', 'hero_workspace.aseprite')
    if not os.path.exists(ws): sys.exit('workspace not found: ' + ws)
    spec = json.load(open(os.path.join(ROOT, 'assets', 'hero_spec.json')))
    tmp = tempfile.mkdtemp(); png, js = os.path.join(tmp, 'sheet.png'), os.path.join(tmp, 'sheet.json')
    ignore = ['REF_3D', 'REF_PHOTO', 'GUIDES'] + ([] if keep_shadow else ['OMBRE_SOL'])
    cmd = [ASEPRITE, '-b'] + sum([['--ignore-layer', n] for n in ignore], []) + [ws, '--sheet', png, '--data', js, '--format', 'json-array', '--sheet-type', 'rows', '--sheet-columns', str(spec['cols'])]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode != 0: sys.exit('Aseprite export failed:\n' + r.stdout + r.stderr)
    data = json.load(open(js)); sheet = Image.open(png).convert('RGBA')
    n = len(spec['frames']); assert len(data['frames']) == n, 'workspace has %d frames, expected %d' % (len(data['frames']), n)
    empty = []
    for i, f in enumerate(data['frames']):
        fr = f['frame']; a = sheet.crop((fr['x'], fr['y'], fr['x'] + fr['w'], fr['y'] + fr['h'])).getchannel('A')
        if sum(a.histogram()[1:]) < 40: empty.append(spec['frames'][i]['name'])
    print('frames drawn: %d / %d' % (n - len(empty), n))
    if empty and not force:
        sys.exit('%d frames are still empty (%s%s) - nothing imported. Finish them or use --force.' % (len(empty), ', '.join(empty[:8]), ' ...' if len(empty) > 8 else ''))
    hero_png = os.path.join(ROOT, 'assets', 'hero.png'); backup = os.path.join(ROOT, 'assets', 'hero_3d_backup.png')
    if os.path.exists(hero_png) and not os.path.exists(backup): shutil.copy(hero_png, backup); print('backup of the current sheet ->', backup)
    sheet.save(hero_png)
    jf = {spec['frames'][i]['name']: {'frame': f['frame'], 'duration': spec['frames'][i]['duration']} for i, f in enumerate(data['frames'])}
    meta = {'app': 'veexing-force hero (hand-drawn workspace import)', 'image': 'hero.png', 'size': {'w': sheet.width, 'h': sheet.height},
            'anchor': {'x': spec['ax'], 'y': spec['ay']}, 'frameTags': [{'name': t['name'], 'from': t['from'], 'to': t['to'], 'direction': 0} for t in spec['tags']], 'anims': spec['anims']}
    out = {'frames': jf, 'meta': meta}; json.dump(out, open(os.path.join(ROOT, 'assets', 'hero.json'), 'w'), indent=1)
    buf = io.BytesIO(); sheet.save(buf, 'PNG', optimize=True)
    open(os.path.join(ROOT, 'js', 'heroSprites.js'), 'w').write(
        "// generated by tools/import_hero_sheet.py - do not edit\nconst HERO_SHEET = {\n  img: 'data:image/png;base64,%s',\n  json: %s\n};\n" % (base64.b64encode(buf.getvalue()).decode(), json.dumps(out)))
    print('hero imported:', sheet.size, '-> js/heroSprites.js (reload the game)')

if __name__ == '__main__': main()
