"""Ending backdrop drawn in Aseprite: tools/ase/ending_bg.lua (+ shared tools/ase/bglib.lua) -> assets/ending.aseprite (one layer per parallax plane),
layers exported by Aseprite, cropped and embedded in js/endingArt.js (ENDING_ART), drawn by js/ending.js.
usage: python tools/make_ending_bg.py [--preview]   (preview = tools/ending_preview.png, composited like the game at a few scroll positions)"""
import base64, io, json, os, subprocess, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'
OUT = os.path.join(ROOT, 'assets', 'ending'); os.makedirs(OUT, exist_ok=True)
fw = lambda p: p.replace(chr(92), '/')
LAYERS = ['sky', 'sun', 'clouds', 'far', 'sea', 'mid', 'front', 'glow']

def ase(args):
    r = subprocess.run([ASEPRITE, '-b'] + args, capture_output=True, text=True, timeout=900)
    if r.returncode != 0 or 'error' in (r.stdout + r.stderr).lower(): raise RuntimeError(r.stdout + r.stderr)
    return r.stdout

ase_path, meta_path = os.path.join(OUT, 'ending.aseprite'), os.path.join(OUT, 'ending_meta.json')
print(ase(['--script-param', 'out=' + fw(ase_path), '--script-param', 'meta=' + fw(meta_path),
           '--script-param', 'lib=' + fw(os.path.join(ROOT, 'tools', 'ase', 'bglib.lua')), '--script', os.path.join(ROOT, 'tools', 'ase', 'ending_bg.lua')]).strip())
meta = json.load(open(meta_path)); HZ = meta['horizon']
crop = {'sky': (0, 0, 640, HZ), 'clouds': (0, 0, 1280, 175), 'far': (0, HZ - 24, 1280, HZ + 1), 'sea': (0, HZ, 640, 254),
        'mid': (0, 130, 1280, 254), 'front': (0, 60, 1280, 360)}
imgs, off = {}, {}
for name in LAYERS:
    png = os.path.join(OUT, name + '.png'); ase([ase_path, '--layer', name, '--save-as', png])
    im = Image.open(png).convert('RGBA')
    if name in crop: box = crop[name]
    else: box = im.getbbox() or (0, 0, 1, 1)                      # sun, glow: tight box + offset
    im = im.crop(box); im.save(png); imgs[name] = im; off[name] = [box[0], box[1]]
    print(' ', name, im.size, off[name])
meta['off'] = off; json.dump(meta, open(meta_path, 'w'))
entries = []
for name in LAYERS:
    buf = io.BytesIO(); imgs[name].save(buf, 'PNG', optimize=True)
    entries.append("  %s: { img: 'data:image/png;base64,%s', x: %d, y: %d }" % (name, base64.b64encode(buf.getvalue()).decode(), off[name][0], off[name][1]))
open(os.path.join(ROOT, 'js', 'endingArt.js'), 'w').write(
    "// generated by tools/make_ending_bg.py (art: assets/ending/ending.aseprite, tools/ase/ending_bg.lua) - do not edit\nconst ENDING_ART = {\n  meta: %s,\n%s\n};\n" % (json.dumps(meta), ',\n'.join(entries)))
print('js/endingArt.js written')
if '--preview' in sys.argv:
    shots = []
    for scroll in (0, 700, 1500):
        sc = Image.new('RGBA', (640, 360), (0, 0, 0, 255))
        def put(name, par, y=None):
            im = imgs[name]; w = im.width; ox = -int(scroll * par) % w if w > 640 else 0
            for k in (0, 1) if w > 640 else (0,): sc.alpha_composite(im, (off[name][0] - ox + k * w, off[name][1]))
        put('sky', 0); sc.alpha_composite(imgs['sun'], (off['sun'][0], off['sun'][1] + 20))
        put('clouds', 0.12); put('far', 0.2); put('sea', 0); put('mid', 0.5); put('front', 1.0)
        shots.append(sc)
    big = Image.new('RGBA', (1280, 720 * len(shots) // 2 + 0), (0, 0, 0, 255))
    for i, s in enumerate(shots): big.alpha_composite(s.resize((1280, 720), Image.NEAREST).crop((0, 0, 1280, 720)), (0, 0)) if i == 0 else None
    for i, s in enumerate(shots): s.resize((1280, 720), Image.NEAREST).save(os.path.join(ROOT, 'tools', 'ending_preview%d.png' % i))
