"""Ending motorbike drawn in Aseprite: tools/ase/ending_bike.lua (+ tools/ase/bglib.lua) -> assets/ending/bike.aseprite (body_pink | body_cyan | under)
and assets/ending/bike_wheel.aseprite (6 frames), exported by Aseprite and embedded in js/endingBike.js (ENDING_BIKE), drawn by js/ending.js.
usage: python tools/make_ending_bike.py [--preview]   (preview = tools/bike_preview.png, 6x)"""
import base64, io, json, os, subprocess, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'
OUT = os.path.join(ROOT, 'assets', 'ending'); os.makedirs(OUT, exist_ok=True)
fw = lambda p: p.replace(chr(92), '/')

def ase(args):
    r = subprocess.run([ASEPRITE, '-b'] + args, capture_output=True, text=True, timeout=600)
    if r.returncode != 0 or 'error' in (r.stdout + r.stderr).lower(): raise RuntimeError(r.stdout + r.stderr)
    return r.stdout

bike, wheel, meta_p = (os.path.join(OUT, n) for n in ('bike.aseprite', 'bike_wheel.aseprite', 'bike_meta.json'))
print(ase(['--script-param', 'out=' + fw(bike), '--script-param', 'wheel=' + fw(wheel), '--script-param', 'meta=' + fw(meta_p),
           '--script-param', 'lib=' + fw(os.path.join(ROOT, 'tools', 'ase', 'bglib.lua')), '--script', os.path.join(ROOT, 'tools', 'ase', 'ending_bike.lua')]).strip())
meta = json.load(open(meta_p)); imgs = {}
for n in ('body_pink', 'body_cyan', 'under'):
    png = os.path.join(OUT, 'bike_%s.png' % n); ase([bike, '--layer', n, '--save-as', png]); imgs[n] = Image.open(png).convert('RGBA')
sheet = os.path.join(OUT, 'bike_wheel.png'); ase([wheel, '--sheet', sheet, '--sheet-type', 'horizontal']); imgs['wheel'] = Image.open(sheet).convert('RGBA')
def b64(im): buf = io.BytesIO(); im.save(buf, 'PNG', optimize=True); return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()
open(os.path.join(ROOT, 'js', 'endingBike.js'), 'w').write(
    "// generated by tools/make_ending_bike.py (art: assets/ending/bike*.aseprite, tools/ase/ending_bike.lua) - do not edit\nconst ENDING_BIKE = {\n  meta: %s,\n%s\n};\n"
    % (json.dumps(meta), ',\n'.join("  %s: '%s'" % (k, b64(v)) for k, v in imgs.items())))
print('js/endingBike.js written', {k: v.size for k, v in imgs.items()})
if '--preview' in sys.argv:
    S = 6; W, H = meta['w'], meta['h']; big = Image.new('RGBA', (W * S, H * S * 2), (58, 24, 84, 255))
    for row, k in enumerate(('body_pink', 'body_cyan')):
        sc = Image.new('RGBA', (W, H), (0, 0, 0, 0)); ws = meta['wheel']
        for ax in (0, 64):
            sc.alpha_composite(imgs['wheel'].crop((0, 0, ws, ws)), (meta['ox'] + ax - ws // 2, meta['oy'] - 16 - ws // 2))
        sc.alpha_composite(imgs[k]); sc.alpha_composite(imgs['under'])
        big.alpha_composite(sc.resize((W * S, H * S), Image.NEAREST), (0, row * H * S))
    big.save(os.path.join(ROOT, 'tools', 'bike_preview.png'))
