"""Riding sprites for the ending cutscene (js/ending.js): VEEX / ROXY seated on a motorbike, torso leaning into the wind, hands on the bars.
Same pixel-art renderers as the fight sprites (hero_pixel / roxy_pixel), only the pose is new (screen-space targets, see hero_anim.py).
Pipeline: Python renders -> assets/hero_ride_src.aseprite (layers body + rim) -> aseprite.exe (hero_finalize.lua, indexed palette)
          -> assets/hero_ride.aseprite (+ png / json) -> js/rideSprites.js
usage: python tools/make_ride_sprites.py [preview]"""
import base64, io, json, math, os, subprocess, sys
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hero6, hero_anim as HA, hero_pixel, roxy_pixel, asekit
from hero_anim import P, GUARD

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'
FS = hero6.Hero6(look='veex').FS
OX, OY = FS // 2, FS - 10

# seated: hips on the saddle, back leaning forward, arms out to the bars, knees up, feet on the pegs
SEAT = P(GUARD, hx=-10.0, hy=17.0, pitch=0.90, twist=-4.0, yb=8.0, yh=40.0, hp=-30.0, hr=0.0,
         nh=(27.0, 31.0, 6.0), fh=(27.0, 31.0, -4.0), ne=(0.0, -1.0, 0.7), fe=(0.0, -1.0, -0.4),
         nf=(9.0, 3.0, 4.0), ff=(8.0, 3.0, -3.5), nk=(1.0, 0.9, 0.4), fk=(1.0, 0.9, -0.1))
LEAN = P(SEAT, hx=-8.0, hy=15.5, pitch=1.15, hp=-36.0, nh=(27.0, 31.0, 6.0), fh=(27.0, 31.0, -4.0))   # throttle open (fists stay on the bars): flat on the tank
FR = [('ride_0', SEAT, (5.0, 0.0)), ('ride_1', P(SEAT, hy=15.6, hp=-14.0), (4.2, 1.2)), ('ride_2', SEAT, (5.0, 0.0)), ('ride_3', P(SEAT, hy=14.5, hp=-18.0), (4.2, -1.0)),
      ('boost_0', LEAN, (5.0, 0.5)), ('boost_1', P(LEAN, hy=14.6), (5.0, -0.5))]

def render(look, pose, wind, name):
    return (hero_pixel if look == 'veex' else roxy_pixel).render(pose, wind, name)

def sheet_png(look, frames):
    return [(n, *render(look, p, w, n)) for n, p, w in frames]

if __name__ == '__main__':
    if 'preview' in sys.argv:
        sc = 4; big = Image.new('RGBA', (len(FR) * FS * sc, 2 * FS * sc), (52, 36, 100, 255))
        for row, look in enumerate(('veex', 'roxy')):
            for i, (n, b, r) in enumerate(sheet_png(look, FR)):
                b = b.copy(); b.alpha_composite(r); big.alpha_composite(b.resize((FS * sc, FS * sc), Image.NEAREST), (i * FS * sc, row * FS * sc))
        out = os.path.join(ROOT, 'tools', 'ride_preview.png'); big.save(out); print(out); sys.exit()
    assets = os.path.join(ROOT, 'assets'); data = {}
    for look in ('veex', 'roxy'):
        stem = 'hero_ride' if look == 'veex' else 'hero_ride_roxy'
        res = sheet_png(look, FR)
        src = os.path.join(assets, stem + '_src.aseprite')
        asekit.write_ase(src, FS, FS, [{'layers': [b, r], 'duration': 100} for n, b, r in res],
                         [{'name': 'ride', 'from': 0, 'to': 3, 'direction': 0}, {'name': 'boost', 'from': 4, 'to': 5, 'direction': 0}], layer_names=('body', 'rim'))
        out = os.path.join(assets, stem + '.aseprite')
        subprocess.run([ASEPRITE, '-b', src, '--script-param', 'out=' + out.replace(chr(92), '/'), '--script', os.path.join(ROOT, 'tools', 'ase', 'hero_finalize.lua')], check=True, capture_output=True)
        subprocess.run([ASEPRITE, '-b', out, '--sheet', os.path.join(assets, stem + '.png'), '--data', os.path.join(assets, stem + '_ase.json'),
                        '--format', 'json-array', '--sheet-type', 'rows', '--sheet-columns', '6'], check=True, capture_output=True)
        aj = json.load(open(os.path.join(assets, stem + '_ase.json')))
        buf = io.BytesIO(); Image.open(os.path.join(assets, stem + '.png')).convert('RGBA').save(buf, 'PNG', optimize=True)
        data[look] = {'img': 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode(),
                      'frames': {n: aj['frames'][i]['frame'] for i, (n, b, r) in enumerate(res)}}
    open(os.path.join(ROOT, 'js', 'rideSprites.js'), 'w').write(
        "// generated by tools/make_ride_sprites.py (art: assets/hero_ride*.aseprite) - do not edit\nconst RIDE_SHEETS = %s;\nconst RIDE_ANCHOR = { x: %d, y: %d };\n" % (json.dumps(data), OX, OY))
    print('ok', FS)
