"""Stage music generated with the ElevenLabs Music API (instrumental), embedded for the game.
The API key is read from .elevenlabs_key (repo root, git-ignored) or ELEVENLABS_API_KEY; it is never printed.
  assets/music/<name>.mp3   generated tracks (kept: re-running only generates the missing ones)
  js/musicData.js           base64 MP3s (the game runs from file://, where fetching separate audio files is blocked)
js/audio.js plays a track in a crossfaded loop when it exists; the old synthesized song of that stage is kept aside as the fallback.
usage: python tools/make_music.py            generate missing tracks + embed
       python tools/make_music.py level1     regenerate this track (costs ElevenLabs credits) + embed
       python tools/make_music.py --embed    embed only"""
import base64, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'music')

# name: (prompt, length in s). Same tempo / key as the synthesized song it replaces, so the game keeps its colour.
MUSIC = {
    'level1': ('Instrumental 1980s synthwave outrun track for a beat em up video game stage: a rainy neon city street at night. '
               '116 BPM, A minor. Driving gated-reverb drums with a punchy kick and big snare, pulsing analog bass arpeggio in sixteenths, '
               'lush polysynth chords, a bright heroic sawtooth lead melody, arcade energy, gritty and cool. Steady groove all the way, '
               'no intro fade and no outro fade so it can loop, no vocals.', 120),
}

def api_key():
    k = os.environ.get('ELEVENLABS_API_KEY')
    p = os.path.join(ROOT, '.elevenlabs_key')
    if not k and os.path.exists(p): k = open(p, encoding='utf8').read().strip()
    if not k: sys.exit('no ElevenLabs key: put it in .elevenlabs_key (repo root, git-ignored) or ELEVENLABS_API_KEY')
    return k

def generate(names):
    from elevenlabs import ElevenLabs
    client = ElevenLabs(api_key=api_key(), timeout=600)
    os.makedirs(OUT, exist_ok=True)
    for n in names:
        prompt, secs = MUSIC[n]
        try:
            data = b''.join(client.music.compose(prompt=prompt, music_length_ms=secs * 1000, force_instrumental=True, output_format='mp3_44100_96'))
        except Exception as e:
            sys.exit('ElevenLabs error on %s: %s' % (n, str(e).replace(api_key(), '***')))
        open(os.path.join(OUT, n + '.mp3'), 'wb').write(data)
        print('generated', n, len(data) // 1024, 'KB')

def embed():
    rows = []
    for n in MUSIC:
        f = os.path.join(OUT, n + '.mp3')
        if os.path.exists(f): rows.append("  %s: '%s'" % (n, base64.b64encode(open(f, 'rb').read()).decode()))
    js = ('// generated by tools/make_music.py (ElevenLabs music, sources in assets/music/) - do not edit\n'
          'const MUSIC_DATA = {\n%s\n};\n') % ',\n'.join(rows)
    open(os.path.join(ROOT, 'js', 'musicData.js'), 'w').write(js)
    print('js/musicData.js:', len(rows), 'tracks,', len(js) // 1024, 'KB')

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if '--embed' not in sys.argv:
        todo = args or [n for n in MUSIC if not os.path.exists(os.path.join(OUT, n + '.mp3'))]
        bad = [n for n in todo if n not in MUSIC]
        if bad: sys.exit('unknown track: ' + ', '.join(bad))
        if todo: generate(todo)
    embed()
