"""Stage backdrops drawn in Aseprite: tools/ase/level<N>_bg.lua (+ shared helpers tools/ase/bglib.lua) -> assets/levels/level<N>.aseprite
(one layer per parallax plane). Each layer is exported by Aseprite, cropped to its useful size, and ALL the built stages are embedded in
js/levelArt.js (LEVEL_ART[N-1]); js/levels.js (BG.drawArt) draws them instead of the procedural backdrop.
usage: python tools/make_level_bg.py <N> [--preview]   (preview = composited screens at each arena -> tools/level<N>_preview.png)"""
import base64, io, json, os, subprocess, sys
from PIL import Image, ImageChops

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASEPRITE = r'F:\Dev\Tooling\aseprite\build\bin\aseprite.exe'
OUT = os.path.join(ROOT, 'assets', 'levels'); os.makedirs(OUT, exist_ok=True)
LAYERS = ['sky', 'far', 'mid', 'floor', 'facade', 'glow', 'flicker', 'bulbsA', 'bulbsB']
SMALL = ('flicker', 'bulbsA', 'bulbsB')          # additive overlays kept as small cut-outs + offset
fw = lambda p: p.replace(chr(92), '/')

def ase(args):
    r = subprocess.run([ASEPRITE, '-b'] + args, capture_output=True, text=True, timeout=600)
    if r.returncode != 0 or 'error' in (r.stdout + r.stderr).lower(): raise RuntimeError(r.stdout + r.stderr)
    return r.stdout

def build(lv):
    ase_path, meta_path = os.path.join(OUT, 'level%d.aseprite' % lv), os.path.join(OUT, 'level%d_meta.json' % lv)
    print(ase(['--script-param', 'out=' + fw(ase_path), '--script-param', 'meta=' + fw(meta_path),
               '--script-param', 'lib=' + fw(os.path.join(ROOT, 'tools', 'ase', 'bglib.lua')),
               '--script', os.path.join(ROOT, 'tools', 'ase', 'level%d_bg.lua' % lv)]).strip())
    meta = json.load(open(meta_path)); W, H, FL = meta['width'], meta['height'], meta['floor']
    crop = {'sky': (0, 0, 640, FL), 'far': (0, 0, meta['farW'], FL), 'mid': (0, 0, meta['midW'], FL), 'floor': (0, FL, W, H),
            'facade': (0, 0, W, meta.get('facadeH', 290)), 'glow': (0, 0, W, H)}
    imgs = {}; meta['off'] = {}
    for name in LAYERS:
        png = os.path.join(OUT, 'level%d_%s.png' % (lv, name))
        ase([ase_path, '--layer', name, '--save-as', png])
        im = Image.open(png).convert('RGBA')
        if name in SMALL:
            bb = im.getbbox() or (0, 0, 1, 1); im = im.crop(bb); off = [bb[0], bb[1]]
        else:
            im = im.crop(crop[name]); off = [crop[name][0], crop[name][1]]
        im.save(png); imgs[name] = (im, off); meta['off'][name] = off
        print(' ', name, im.size, off)
    json.dump(meta, open(meta_path, 'w'))
    return meta, imgs

def embed():
    blocks = []
    for k in range(1, 9):
        mp = os.path.join(OUT, 'level%d_meta.json' % k)
        if not os.path.exists(mp): continue
        m = json.load(open(mp)); entries = []
        for name in LAYERS:
            buf = io.BytesIO(); Image.open(os.path.join(OUT, 'level%d_%s.png' % (k, name))).save(buf, 'PNG', optimize=True); off = m['off'][name]
            entries.append("    %s: { img: 'data:image/png;base64,%s', x: %d, y: %d }" % (name, base64.b64encode(buf.getvalue()).decode(), off[0], off[1]))
        blocks.append('  %d: {\n    meta: %s,\n%s\n  }' % (k - 1, json.dumps(m), ',\n'.join(entries)))
    js = ('// generated by tools/make_level_bg.py (art: assets/levels/level<N>.aseprite, tools/ase/level<N>_bg.lua) - do not edit\n'
          'const LEVEL_ART = {\n%s\n};\n') % ',\n'.join(blocks)
    open(os.path.join(ROOT, 'js', 'levelArt.js'), 'w').write(js); print('js/levelArt.js:', len(blocks), 'stage(s),', len(js) // 1024, 'KB')

def preview(lv, meta, imgs):
    shots = []
    for cam in [max(0, s - 160) for s in meta['stops']]:
        sc = Image.new('RGBA', (640, 360), (0, 0, 0, 255))
        for name, par in (('sky', 0), ('far', meta['far']), ('mid', meta['mid']), ('floor', 1), ('facade', 1)):
            im, off = imgs[name]; sc.alpha_composite(im.crop((int(cam * par), 0, int(cam * par) + 640, im.height)), (0, off[1]))
        for name in ('glow', 'flicker', 'bulbsA'):
            im, off = imgs[name]; layer = Image.new('RGBA', (640, 360), (0, 0, 0, 0)); layer.paste(im, (off[0] - cam, off[1]))
            a = layer.split()[3]; add = Image.merge('RGB', [ImageChops.multiply(ch, a) for ch in layer.split()[:3]])
            sc = Image.merge('RGBA', list(ImageChops.add(sc.convert('RGB'), add).split()) + [Image.new('L', (640, 360), 255)])
        shots.append(sc)
    pv = Image.new('RGB', (1280, 360 * ((len(shots) + 1) // 2)))
    for i, s in enumerate(shots): pv.paste(s.convert('RGB'), ((i % 2) * 640, (i // 2) * 360))
    out = os.path.join(ROOT, 'tools', 'level%d_preview.png' % lv); pv.save(out); print('preview', out)

if __name__ == '__main__':
    lv = int(next((a for a in sys.argv[1:] if a.isdigit()), '1'))
    meta, imgs = build(lv)
    embed()
    if '--preview' in sys.argv: preview(lv, meta, imgs)
