"""Build js/assets.js (embedded base64 images) from public/veex.png (+ public/roxy.png: title photo of the second hero).
Embedding keeps the game runnable by double-clicking index.html (no server, no canvas taint)."""
import base64, io, os
from PIL import Image, ImageEnhance

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = Image.open(os.path.join(root, "public", "veex.png")).convert("RGB")

def b64(img, fmt, **kw):
    buf = io.BytesIO(); img.save(buf, fmt, **kw)
    return "data:image/%s;base64,%s" % (fmt.lower().replace("jpeg", "jpeg"), base64.b64encode(buf.getvalue()).decode())

# Head: tight crop on hair + face, stretched to chibi proportions, punchy 80s grade.
head = src.crop((205, 70, 905, 1085)).resize((60, 68), Image.LANCZOS)
head = ImageEnhance.Color(head).enhance(1.35)
head = ImageEnhance.Contrast(head).enhance(1.25)
head = ImageEnhance.Brightness(head).enhance(1.08)

# Title portrait: whole photo, mildly graded.
port = src.resize((320, 480), Image.LANCZOS)
port = ImageEnhance.Color(port).enhance(1.25)
port = ImageEnhance.Contrast(port).enhance(1.15)

def title_photo(img):
    img = img.resize((320, 480), Image.LANCZOS)
    img = ImageEnhance.Color(img).enhance(1.25)
    return ImageEnhance.Contrast(img).enhance(1.15)

rows = ["  head: '%s'" % b64(head, "PNG"), "  portrait: '%s'" % b64(port, "JPEG", quality=82)]
roxy = os.path.join(root, "public", "roxy.png")
if os.path.exists(roxy): rows.append("  portrait_roxy: '%s'" % b64(title_photo(Image.open(roxy).convert("RGB")), "JPEG", quality=82))
js = "// generated by tools/make_assets.py - do not edit\nconst ASSETS = {\n%s\n};\n" % ",\n".join(rows)
open(os.path.join(root, "js", "assets.js"), "w").write(js)
print("ok", len(js))
